# Generated by Django 2.2.3 on 2019-07-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190702_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='conf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='div',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='home',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='last',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='non_conf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='road',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='streak',
            field=models.FloatField(),
        ),
    ]
